#include "phy/pilot_utils.h"

#include <gtest/gtest.h>

#include <array>

// ── golden data from IEEE 802.11a-1999 Annex G ────────────────────────────────
//
// Table G.23 gives the pilot-polarity multiplier p_i for 7 consecutive OFDM
// symbols (SIGNAL, DATA 1..6): {1, 1, 1, 1, -1, -1, -1}. Per 17.3.5.9 this
// sequence is generated by the *same* 7-bit LFSR (x^7 + x^4 + 1, all-ones
// seed) as the data scrambler, and p_i = +1 when the generator's output bit
// is 0, or -1 when it is 1. This is independently confirmed by the existing
// ForwardErrorCorrection.ScramblerAllOnesSeed golden test: the first 7 bits
// of that PRBS are 0,0,0,0,1,1,1, which maps to exactly {1,1,1,1,-1,-1,-1}.

/// Table G.23: pilot polarity multiplier for symbols {SIGNAL, DATA1..DATA6}.
constexpr std::array<double, 7> kPilotPolarityGolden = {1, 1, 1, 1, -1, -1, -1};

/// 17.3.5.9 / Table G.23: PilotLFSR must reproduce the standard's pilot
/// polarity sequence for the first 7 OFDM symbols of a packet.
///
/// NOTE: as of this writing, this test is expected to FAIL. PilotLFSR reads
/// out the top register bit (state_ >> 6) *before* folding in the feedback,
/// whereas the standard (and this codebase's own data_scrambler_prbs /
/// LFSRStep_) defines the PRBS output as the feedback bit itself
/// (regs[3] ^ regs[6]). Because of this the first several outputs are
/// phase-shifted/inverted relative to Annex G, so the actual OFDM pilot
/// subcarriers will not match a compliant transmitter or receiver.
TEST(PilotUtils, PolaritySequenceMatchesAnnexGTableG23)
{
    wifi80211a::PilotLFSR lfsr;
    for (int i = 0; i < 7; ++i)
    {
        EXPECT_EQ(lfsr.next_polarity(), kPilotPolarityGolden[i])
            << "symbol index " << i << " (0=SIGNAL, 1..6=DATA1..DATA6)";
    }
}

/// reset() must restore the LFSR to its initial state, so the sequence from
/// a freshly-constructed PilotLFSR repeats after a reset.
TEST(PilotUtils, ResetRestartsSequence)
{
    wifi80211a::PilotLFSR lfsr;
    std::array<double, 7> first_pass{};
    for (double& v : first_pass) v = lfsr.next_polarity();

    lfsr.reset();
    for (const double expected : first_pass)
    {
        EXPECT_EQ(lfsr.next_polarity(), expected);
    }
}
